### PR TITLE
Update to webpack 5

### PR DESCRIPTION
**Pull request by josemartos**
When using this plugin in projects using webpack 5, it throws an error. This update addresses the problem.

### CODE REVIEW

**Comment by mkurtas** [comment]
@josemartos i am going to review your changes. We need support there webpack 5 quickly.

**Comment by josemartos** [comment]
Hi @mkurtas thanks a lot for merging. 

I have tried to test it locally using webpack 5, and it doesn't look to work, even after these changes (which are however letting the bundle being built for production, before it was throwing an error). It does work with webpack 4 though. 

It's like the async-define queue is not kept, so the dependency "external" is not available on other async script and it throws an error. It must be something else, related to how webpack 5 is treating the plugin and how the bundle is generated, even if it's wrapped in async-define. Not sure where to look at the moment.

Thanks again!

**Comment by mkurtas** [comment]
> Hi @mkurtas thanks a lot for merging.
> 
> I have tried to test it locally using webpack 5, and it doesn't look to work, even after these changes (which are however letting the bundle being built for production, before it was throwing an error). It does work with webpack 4 though.
> 
> It's like the async-define queue is not kept, so the dependency "external" is not available on other async script and it throws an error. It must be something else, related to how webpack 5 is treating the plugin and how the bundle is generated, even if it's wrapped in async-define. Not sure where to look at the moment.
> 
> Thanks again!

Thanks for feedback, i am going to fix it tomorrow. There are still one error there:

```
[mkurtas@Mateusz-Dell app-order-history] $ node --trace-deprecation node_modules/webpack/bin/webpack.js
(node:382840) [DEP_WEBPACK_COMPILATION_OPTIMIZE_CHUNK_ASSETS] DeprecationWarning: optimizeChunkAssets is deprecated (use Compilation.hooks.processAssets instead and use one of Compilation.PROCESS_ASSETS_STAGE_* as stage option)
    at /home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack-async-define/index.js:25:45
    at Hook.eval [as call] (eval at create (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:100:1)
    at Hook.CALL_DELEGATE [as _call] (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/node_modules/tapable/lib/Hook.js:14:14)
    at Compiler.newCompilation (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/lib/Compiler.js:993:26)
    at /home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/lib/Compiler.js:1035:29
    at Hook.eval [as callAsync] (eval at create (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/lib/Compiler.js:1030:28)
    at /home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/lib/Compiler.js:473:12
    at Compiler.readRecords (/home/mkurtas/Pracownia/TES/source/portal/app-order-history/node_modules/webpack/lib/Compiler.js:871:11)
```

**Comment by josemartos** [comment]
Awesome mate, thanks for the feedback!

**Pull request merged**
